name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clickable
        run: |
          sudo apt install adb git python3 python3-pip python3-setuptools
          pip3 install --user clickable-ut --upgrade
          echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

      - uses: actions/setup-node@v2
        with:
           node-version: '14.x'

      - name: Build App
        run: clickable build --output dist

      - uses: actions/upload-artifact@v3
        with:
          name: cathodetube
          path: dist/*
